export const NAVIGATE_ROUTES = {
  HOME_PAGE: '/',
  PROFILE_PAGE: '/my-profile',
  CREATE_EVENT_PAGE: '/organizer/create-event',
  MY_EVENTS_PAGE: '/organizer/my-events',
  MY_TICKETS_PAGE: '/my-ticket',
  SEARCH_PAGE: '/search',
  EVENT_PAGE: '/event',
  TUTORIAL_PAGE: '/instruction',
  POLICY_PAGE: '/policy',
  LEGAL_DOCUMENT_PAGE: '/legal-document',
  CHANGE_PASSWORD_PAGE: '/change-password',
  EVENT_ANALYSTICS_PAGE: '/event-analytics',
  EVENT_DETAIL_PAGE: '/event',
  NONE: '/',
  TUTORIAL_PAGE_CREATE_EVENT: '/instruction?tab=organizer&activeTab=create-event',
  TUTORIAL_PAGE_SIGN_IN: '/instruction?tab=user&activeTab=sign-in',
  TUTORIAL_PAGE_SIGN_UP: '/instruction?tab=user&activeTab=sign-up',
  TUTORIAL_UPDATE_INFO: '/instruction?tab=user&activeTab=update-profile',
  TUTORIAL_PAGE_SEARCH: '/instruction?tab=user&activeTab=search-event',
  TUTORIAL_PAGE_FOLLOW_EVENT: '/instruction?tab=user&activeTab=follow-event',
  TUTORIAL_PAGE_BUY_TICKET: '/instruction?tab=user&activeTab=buy-ticket',
  TUTORIAL_PAGE_VIEW_TICKET_QR: '/instruction?tab=user&activeTab=view-qr',
  TUTORIAL_PAGE_MANAGE_EVENT: '/instruction?tab=organizer&activeTab=org-management',
  TUTORIAL_PAGE_CHECKIN_EVENT: '/instruction?tab=organizer&activeTab=org-checkin',
};